// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getEnvironment(args?: GetEnvironmentArgs, opts?: pulumi.InvokeOptions): Promise<GetEnvironmentResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("honeycombio:index/getEnvironment:getEnvironment", {
        "detailFilters": args.detailFilters,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getEnvironment.
 */
export interface GetEnvironmentArgs {
    detailFilters?: inputs.GetEnvironmentDetailFilter[];
    id?: string;
}

/**
 * A collection of values returned by getEnvironment.
 */
export interface GetEnvironmentResult {
    readonly color: string;
    readonly deleteProtected: boolean;
    readonly description: string;
    readonly detailFilters?: outputs.GetEnvironmentDetailFilter[];
    readonly id: string;
    readonly name: string;
    readonly slug: string;
}
export function getEnvironmentOutput(args?: GetEnvironmentOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetEnvironmentResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("honeycombio:index/getEnvironment:getEnvironment", {
        "detailFilters": args.detailFilters,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getEnvironment.
 */
export interface GetEnvironmentOutputArgs {
    detailFilters?: pulumi.Input<pulumi.Input<inputs.GetEnvironmentDetailFilterArgs>[]>;
    id?: pulumi.Input<string>;
}
