// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Slo extends pulumi.CustomResource {
    /**
     * Get an existing Slo resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SloState, opts?: pulumi.CustomResourceOptions): Slo {
        return new Slo(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'honeycombio:index/slo:Slo';

    /**
     * Returns true if the given object is an instance of Slo.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Slo {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Slo.__pulumiType;
    }

    /**
     * The dataset this SLO is created in. Will be deprecated in a future release. Must be the same dataset as the SLI unless
     * the SLI Derived Column is Environment-wide.
     */
    declare public readonly dataset: pulumi.Output<string>;
    /**
     * The datasets the SLO is evaluated on.
     */
    declare public readonly datasets: pulumi.Output<string[]>;
    /**
     * A description of the SLO's intent and context.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The name of the SLO.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The alias of the Derived Column that will be used as the SLI to indicate event success. The derived column used as the
     * SLI must be in the same dataset as the SLO. Additionally, the column evaluation should consistently return nil, true, or
     * false, as these are the only valid values for an SLI.
     */
    declare public readonly sli: pulumi.Output<string>;
    /**
     * A map of tags to assign to the resource.
     */
    declare public readonly tags: pulumi.Output<{[key: string]: string}>;
    /**
     * The percentage of qualified events that you expect to succeed during the `time_period`.
     */
    declare public readonly targetPercentage: pulumi.Output<number>;
    /**
     * The time period, in days, over which your SLO will be evaluated.
     */
    declare public readonly timePeriod: pulumi.Output<number>;

    /**
     * Create a Slo resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SloArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SloArgs | SloState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SloState | undefined;
            resourceInputs["dataset"] = state?.dataset;
            resourceInputs["datasets"] = state?.datasets;
            resourceInputs["description"] = state?.description;
            resourceInputs["name"] = state?.name;
            resourceInputs["sli"] = state?.sli;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["targetPercentage"] = state?.targetPercentage;
            resourceInputs["timePeriod"] = state?.timePeriod;
        } else {
            const args = argsOrState as SloArgs | undefined;
            if (args?.sli === undefined && !opts.urn) {
                throw new Error("Missing required property 'sli'");
            }
            if (args?.targetPercentage === undefined && !opts.urn) {
                throw new Error("Missing required property 'targetPercentage'");
            }
            if (args?.timePeriod === undefined && !opts.urn) {
                throw new Error("Missing required property 'timePeriod'");
            }
            resourceInputs["dataset"] = args?.dataset;
            resourceInputs["datasets"] = args?.datasets;
            resourceInputs["description"] = args?.description;
            resourceInputs["name"] = args?.name;
            resourceInputs["sli"] = args?.sli;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["targetPercentage"] = args?.targetPercentage;
            resourceInputs["timePeriod"] = args?.timePeriod;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Slo.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Slo resources.
 */
export interface SloState {
    /**
     * The dataset this SLO is created in. Will be deprecated in a future release. Must be the same dataset as the SLI unless
     * the SLI Derived Column is Environment-wide.
     */
    dataset?: pulumi.Input<string>;
    /**
     * The datasets the SLO is evaluated on.
     */
    datasets?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A description of the SLO's intent and context.
     */
    description?: pulumi.Input<string>;
    /**
     * The name of the SLO.
     */
    name?: pulumi.Input<string>;
    /**
     * The alias of the Derived Column that will be used as the SLI to indicate event success. The derived column used as the
     * SLI must be in the same dataset as the SLO. Additionally, the column evaluation should consistently return nil, true, or
     * false, as these are the only valid values for an SLI.
     */
    sli?: pulumi.Input<string>;
    /**
     * A map of tags to assign to the resource.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The percentage of qualified events that you expect to succeed during the `time_period`.
     */
    targetPercentage?: pulumi.Input<number>;
    /**
     * The time period, in days, over which your SLO will be evaluated.
     */
    timePeriod?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a Slo resource.
 */
export interface SloArgs {
    /**
     * The dataset this SLO is created in. Will be deprecated in a future release. Must be the same dataset as the SLI unless
     * the SLI Derived Column is Environment-wide.
     */
    dataset?: pulumi.Input<string>;
    /**
     * The datasets the SLO is evaluated on.
     */
    datasets?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A description of the SLO's intent and context.
     */
    description?: pulumi.Input<string>;
    /**
     * The name of the SLO.
     */
    name?: pulumi.Input<string>;
    /**
     * The alias of the Derived Column that will be used as the SLI to indicate event success. The derived column used as the
     * SLI must be in the same dataset as the SLO. Additionally, the column evaluation should consistently return nil, true, or
     * false, as these are the only valid values for an SLI.
     */
    sli: pulumi.Input<string>;
    /**
     * A map of tags to assign to the resource.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The percentage of qualified events that you expect to succeed during the `time_period`.
     */
    targetPercentage: pulumi.Input<number>;
    /**
     * The time period, in days, over which your SLO will be evaluated.
     */
    timePeriod: pulumi.Input<number>;
}
